title: Human–AI Co-Creativity Consortium
description: Advancing human–AI creative problem solving in science and beyond.
url: https://text-machine-lab.github.io
baseurl: "/hai3c"     # keep empty when publishing at username.github.io/<repo> use "/<repo>" if not using a custom domain

remote_theme: "mmistakes/minimal-mistakes"

# Plugins allowed on GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

# Build
markdown: kramdown
theme: null  # required when using remote_theme


# Minimal Mistakes settings
minimal_mistakes_skin: "air"   # other options: default, dark, mint, sunrise, etc.
logo: /assets/hands-colored-hai3c.png         # optional; add your logo to /assets
breadcrumbs: true
search: true

# Display site header / navigation
header:
  overlay_color: "#000"      # optional aesthetic
  overlay_filter: "0.3"      # optional
  show_overlay_logo: false   # keep false unless you want a logo on hero images
  show_nav: true

# Navigation
collections:
  posts:
    output: true
    permalink: /updates/:title/

# Header navigation
main:
  - title: "Home"
    url: /
  - title: "Science"
    url: /science/
  - title: "Practice & Innovation"
    url: /practice/
  - title: "Join the Beta"
    url: /join/
  - title: "Updates"
    url: /updates/

# Logos
sass:
  load_paths:
    - assets
include: ["assets"]

# Footer links (edit to taste)
footer:
  links:
    - label: "Discussion"
      icon: "fas fa-comments"
      url: "https://github.com/text-machine-lab/hai3c/discussions"
    #- label: "Email"
    #  url: "mailto:info@haicc.org"
    - label: "Privacy"
      url: /privacy/

# SEO & Analytics
author:
  name: Human–AI Co-Creativity Consortium
#twitter:
#  username: hai3c      # optional
google_analytics: ""   # paste GA4 measurement ID later; Minimal Mistakes will insert it

